theme: jekyll-theme-minimal
title: "Welcome to Libi Saad's Website!"
logo : 'logo.jpg'
title_align: left
description: "M.Sc. in Life Sciences at the Weizmann Institute of Science"
show_downloads: false

