theme: jekyll-theme-minimal
title: "Welcome to Libi Saad's Website!"
description: "M.Sc. in Life Sciences at the Weizmann Institute of Science"
logo : 'logo.jpg'
title_align: center
show_downloads: false

